language: generic
deploy:
  provider: s3
  access_key_id: AKIAJZXKM35QQV2EKK6Q
  secret_access_key: 
    secure: AAgkIArTShQ3yXnLFCJndAMEQIwmuh03kWKMg0KG3kaSOD1RxOWN2U7ZTxWdZWVq4DsC2VavbunEN18nXjG//UxglBqHasxtK+8NWlGioVQgcapjouChstE1frlhXcg54wDjBnNfp5Yf2h8A7E1LGY8ZQ/fDpKbrGynvtLdRmtjQtodXbSE0Kvvm5Jrp8oL7XdeEKTyDpjxlF0sXq/MDeju0LM0miCTJ8iQpODIG8njW8wST6LhzGf7xjOhJZ+PY0q1bA7pQgR9NiAIHP+6UQB5WKzjS4XRgutXJtBKwFtPh37EtqhJjVCGpLez5KfMHDL3UvRuLUq1x2t2iZrzBboAZO01yXnrq4nQsjknKb7jlt4XJJPzKzza5l9P7SKYeRP4cfvqwEsUOMuwv69SI/CAUApBWLurB1agfXLECsVDegIvOXrArUmpWiEwyrDuFPeb4333BadSZkaASt/9wAuL4LrU/yBZEjJKngWSO0JZ9hpPa9g8cdbH4UMGVenq4ghc2PESBPdJj3CASNGnI0S0GXu4jKww4V38URHbR+vSv2oZu1Rz2ug0nMqhf5RUzoQqYMCfYWhfLAQAYCWJjRDWay5cAdhZ3lQo3FQ26oPEb1CXJohtz0+j8D/4/m1SsFoBs33RxwzCa8A4z2IJlDUqI1TZMkA+X48T35BxaQno=
  bucket: d2g-swagger-ui
  region: eu-central-1
  acl: public_read
  skip_cleanup: true
  on:
    repo: AvoJFB/d2g-swagger-ui

